{
  "name": "ValueError",
  "version": "0.0.1",
  "description": "ValueError, an instance of Error, for Node.js",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "node_modules/eslint/bin/eslint.js index.js tests/**/*.js"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/thefourtheye/ValueError.git"
  },
  "keywords": [
    "Error",
    "ValueError",
    "custom",
    "error"
  ],
  "author": "Sakthipriyan Vairamani <thechargingvolcano@gmail.com> (thefourtheye)",
  "license": "GPL-3.0",
  "bugs": {
    "url": "https://github.com/thefourtheye/ValueError/issues"
  },
  "homepage": "https://github.com/thefourtheye/ValueError",
  "devDependencies": {
    "eslint": "^1.10.3"
  }
}
