{
  "name": "valueerror",
  "version": "0.0.2",
  "description": "ValueError, an instance of Error, for Node.js",
  "main": "index.js",
  "scripts": {
    "test": "npm run lint && node_modules/mocha/bin/mocha tests/*.js tests/**/*.js",
    "lint": "node_modules/eslint/bin/eslint.js index.js tests/**/*.js"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/thefourtheye/ValueError.git"
  },
  "keywords": [
    "Error",
    "ValueError",
    "custom",
    "error"
  ],
  "author": "Sakthipriyan Vairamani <thechargingvolcano@gmail.com> (thefourtheye)",
  "license": "GPL-3.0",
  "bugs": {
    "url": "https://github.com/thefourtheye/ValueError/issues"
  },
  "homepage": "https://github.com/thefourtheye/ValueError",
  "devDependencies": {
    "chai": "^3.5.0",
    "coveralls": "^2.11.16",
    "eslint": "^3.16.1",
    "istanbul": "^0.4.5",
    "mocha": "^3.4.1"
  }
}
